### ISSUE TITLE
Imports not recognized 

### ISSUE THREAD

**Issue by guneetsura** [pranav750/tool#1]
After executing this command - python spydark.py --dark --url https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/ --bfs --depth 2 

This issue has arrived -->

> Traceback (most recent call last):
  File "/home/kali/Downloads/tool-main/spydark.py", line 5, in <module>
    from crawler.darkweb.bfs import BFSDarkWebCrawler
  File "/home/kali/Downloads/tool-main/crawler/darkweb/bfs.py", line 24, in <module>
    from utils.functions import time_difference, create_directory_for_images, output
  File "/home/kali/Downloads/tool-main/utils/functions.py", line 9, in <module>
    TOR_BROWSER_PATH = config['TOR_BROWSER_PATH']
KeyError: 'TOR_BROWSER_PATH'

**Comment by abhishek-jha-24** [comment]
create a .env file and add the env variables. It would definitely solve the problem

**Comment by guneetsura** [comment]
Yes, done that.

Although, this error still persists on running this command
#python spydark.py --dark --url http://juhanurmihxlp77nkq76byazcldy2hlmovfu2epvl5ankdibsot4csyd.onion/ --bfs --depth 2     

```
Starting Tor Browser...
Traceback (most recent call last):
  File "/home/kali/Downloads/tool-main/spydark.py", line 99, in <module>
    open_tor_browser()
  File "/home/kali/Downloads/tool-main/utils/functions.py", line 16, in open_tor_browser
    os.startfile(TOR_BROWSER_PATH)
AttributeError: module 'os' has no attribute 'startfile'
```

**Comment by Amaan-8808** [comment]
> Yes, done that.
> 
> Although, an error still persists on running this command
> 
> ```
> python spydark.py --dark --url http://juhanurmihxlp77nkq76byazcldy2hlmovfu2epvl5ankdibsot4csyd.onion/ --bfs --depth 2     
> ```
> 
> The error:
> 
> ```
> Starting Tor Browser...
> Traceback (most recent call last):
>   File "/home/kali/Downloads/tool-main/spydark.py", line 99, in <module>
>     open_tor_browser()
>   File "/home/kali/Downloads/tool-main/utils/functions.py", line 16, in open_tor_browser
>     os.startfile(TOR_BROWSER_PATH)
> AttributeError: module 'os' has no attribute 'startfile'
> ```

Try Running the tool on windows not linux

**Comment by guneetsura** [comment]
> > Yes, done that.
> > Although, an error still persists on running this command
> > ```
> > python spydark.py --dark --url http://juhanurmihxlp77nkq76byazcldy2hlmovfu2epvl5ankdibsot4csyd.onion/ --bfs --depth 2     
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The error:
> > ```
> > Starting Tor Browser...
> > Traceback (most recent call last):
> >   File "/home/kali/Downloads/tool-main/spydark.py", line 99, in <module>
> >     open_tor_browser()
> >   File "/home/kali/Downloads/tool-main/utils/functions.py", line 16, in open_tor_browser
> >     os.startfile(TOR_BROWSER_PATH)
> > AttributeError: module 'os' has no attribute 'startfile'
> > ```
> 
> Try Running the tool on windows not linux

Running on windows was a little complicated. My path was set but it was not working for some reason.
Although I changed the 'functions.py' file under the 'utils' folder. And it seems to work well now!
This is what I did

```
# Importing the required libraries
import os, shutil
import time
import subprocess, sys

opener = "open" if sys.platform == "darwin" else "xdg-open"

# For accessing the values from the .env file
from dotenv import dotenv_values

config = dotenv_values(".env")
TOR_BROWSER_PATH = config['TOR_BROWSER_PATH']

# Starting Tor Browser
def open_tor_browser():

    output("Starting Tor Browser...", True)

    #os.startfile(TOR_BROWSER_PATH)
    subprocess.call([opener, TOR_BROWSER_PATH])
    time.sleep(10)

    output("Tor Browser Started.", False)

# Calculate time difference
```

I basically just imported subprocess and sys and called a file using opener variable. You can see the rest!
I commented out os.startfile as it had trouble in recognizing.

**Comment by guneetsura** [comment]
Now that the tor browser is running (even on windows), I ran this command
```
python spydark.py --dark --url http://s4k4ceiapwwgcm3mkb6e4diqecpo7kvdnfr5gg7sph7jjppqkvwwqtyd.onion --bfs --depth 2
```

The command opens up the tor browser, and nothing really happens in the browser (unless we're expecting this, it isn't the real issue). The real issue is what I see in the terminal. Check below.

```
Crawl http://s4k4ceiapwwgcm3mkb6e4diqecpo7kvdnfr5gg7sph7jjppqkvwwqtyd.onion with depth 2 on dark web
--------------------
Clearing the results directory...
Results directory cleared.
--------------------
--------------------
Starting Tor Browser...
Tor Browser Started.
--------------------
Page not found... http://s4k4ceiapwwgcm3mkb6e4diqecpo7kvdnfr5gg7sph7jjppqkvwwqtyd.onion
--------------------
Generating Wordcloud...
Traceback (most recent call last):
  File "C:\Users\gunee\Downloads\tool-main\spydark.py", line 102, in <module>
    result = dark_web_object.crawl()
  File "C:\Users\gunee\Downloads\tool-main\crawler\darkweb\bfs.py", line 277, in crawl
    top_five_keywords = create_wordcloud(self.crawled_links)
  File "C:\Users\gunee\Downloads\tool-main\utils\wordcloud.py", line 61, in create_wordcloud
    top_five_keywords = display_wordcloud(wc_words)
  File "C:\Users\gunee\Downloads\tool-main\utils\wordcloud.py", line 31, in display_wordcloud
    wordc.generate(open(os.path.join(os.path.dirname( __file__ ), '..', 'static', 'wc_words.txt'), encoding = 'utf-8').read())
  File "C:\Users\gunee\AppData\Local\Programs\Python\Python310\lib\site-packages\wordcloud\wordcloud.py", line 639, in generate
    return self.generate_from_text(text)
  File "C:\Users\gunee\AppData\Local\Programs\Python\Python310\lib\site-packages\wordcloud\wordcloud.py", line 621, in generate_from_text
    self.generate_from_frequencies(words)
  File "C:\Users\gunee\AppData\Local\Programs\Python\Python310\lib\site-packages\wordcloud\wordcloud.py", line 410, in generate_from_frequencies
    raise ValueError("We need at least 1 word to plot a word cloud, "
ValueError: We need at least 1 word to plot a word cloud, got 0.
```
